Update tensorrt.py (#6034)
Changes in Tensorflow contrib:
https://github.com/tensorflow/tensorflow/commit/304faf0444260912b6996d39227417c09561c37e

Causes tensortt.py to fail. 

```
AttributeError: 'module' object has no attribute 'get_signature_def_by_key'
```
Replace `tf.contrib.saved_model.get_signature_def_by_key` with `meta_graph_def.signature_def`
Former-commit-id: 7761275f8481b24dfdab050baf44c16ef28fa3b3 [formerly d5af1a9a9879373234da3cda61f7731cbc22bda3] [formerly 2a20327c127b1ad8b64d8c56c932c48684d7b8ce] [formerly e2e03216a266a103bec2bbe869007312cede14da [formerly 184b977000d624860bcf1700125925be0f426035] [formerly d32d957a02f5cffb745a4da0d78f8432e2c52fd4]]
Former-commit-id: e2e03216a266a103bec2bbe869007312cede14da [formerly 184b977000d624860bcf1700125925be0f426035]
Former-commit-id: 0722b01cecfd62d7e75d03f1bc14fc55801857b7
Former-commit-id: cf8cde9e080dc3bf7b3eb252808ac7d16ff44e34