ensure output directory exists
The neural programmer model fails the first time it's run, if the output directory folder does not already exist. In this case "../model" does not exist and the function fails because the mkdir function doesn't appear to create parent folders. 
Error: 
tensorflow.python.framework.errors_impl.NotFoundError: ../model//modeltemp/
Former-commit-id: 83f1f0b4e0bf1c9ca1e524d8bcc0ed5c51e4f6c2 [formerly 2a3041e3d1f8ee5202a37af448d38cb95ee68f1c] [formerly 579d8dd0f34db508df7b327331b710942ea05cba] [formerly e406e75820c4b22beaf617b07f66fe9008cdd8f2 [formerly 39bb28d0c5189bdde6492d22b081014d0d0a5cf9] [formerly 6601008ff2e65f9945d471486efadf73b1aac53a]]
Former-commit-id: e406e75820c4b22beaf617b07f66fe9008cdd8f2 [formerly 39bb28d0c5189bdde6492d22b081014d0d0a5cf9]
Former-commit-id: a3c310493cd6cb3939e7b30522927ab154291129
Former-commit-id: be914b43ae94a64836b0cc76cc22b483108c6246