absl_app.run() fails without including `main` as an argument (#6940)
After the change (https://github.com/tensorflow/models/pull/6846/files#diff-965780bf33f2aeca41a33f8eba197c79) I receive the following error:

File "./models/official/mnist/mnist_tpu.py", line 202, in <module>
    absl_app.run()
TypeError: run() missing 1 required positional argument: 'main'

I added main as an argument and it seems to be working fine now.
Former-commit-id: 4da8e2779462a986daa23113b33cbd1d6de8681e [formerly a3cbf346b6c598a5ab38228bf04e63eda984caac] [formerly 770a17ffc7fe371df6b1745883565e929b4371dc] [formerly 809c0995f7f540f51d591f31b946e72623c40eb9 [formerly 3692cd98677dbc3bf95c05e6c47b8014cfc56f86] [formerly 67d34698cfd0dbfab4ba1dbf6dfeea3dcc898aee]] [formerly 11135b4505762b1abeb1ef456c494edeaa4d4cf6 [formerly 1fd3618239ea0f01baa0d534a2b4e5346a4df330 [formerly 625262ad039a5c8be98e67d5fd169baeedc307ef] [formerly e7b21bfd58614f43131be55308dadd619d7773ae]]]
Former-commit-id: 1fd3618239ea0f01baa0d534a2b4e5346a4df330 [formerly 625262ad039a5c8be98e67d5fd169baeedc307ef]
Former-commit-id: df6ba32a422471e80a6d7a71a09851972446b696
Former-commit-id: 9185bfd9e66ae9e4ef75d5386262ce1ca2b643bd
Former-commit-id: 17943eed8c3251d8bd7e0526401f831476d0822e