Update learning_schedules.py
The following error doesn't occur with the above change in code.

Error: Argument must be a dense tensor: range(0, 3) - got shape [3], but wanted []

The range function on the vairable 'num_boundaries' should be a list! Please merge this request!
Former-commit-id: ef84dca1050762a816984fab7323c5cfea683dde
Former-commit-id: 5fd45d252650037f462b8a72ecb104ad3a890f86