Update tensorrt.py (#6034)
Changes in Tensorflow contrib:
https://github.com/tensorflow/tensorflow/commit/304faf0444260912b6996d39227417c09561c37e

Causes tensortt.py to fail. 

```
AttributeError: 'module' object has no attribute 'get_signature_def_by_key'
```
Replace `tf.contrib.saved_model.get_signature_def_by_key` with `meta_graph_def.signature_def`
Former-commit-id: d32d957a02f5cffb745a4da0d78f8432e2c52fd4
Former-commit-id: 184b977000d624860bcf1700125925be0f426035