absl_app.run() fails without including `main` as an argument (#6940)
After the change (https://github.com/tensorflow/models/pull/6846/files#diff-965780bf33f2aeca41a33f8eba197c79) I receive the following error:

File "./models/official/mnist/mnist_tpu.py", line 202, in <module>
    absl_app.run()
TypeError: run() missing 1 required positional argument: 'main'

I added main as an argument and it seems to be working fine now.
Former-commit-id: e7b21bfd58614f43131be55308dadd619d7773ae
Former-commit-id: 625262ad039a5c8be98e67d5fd169baeedc307ef