ensure output directory exists
The neural programmer model fails the first time it's run, if the output directory folder does not already exist. In this case "../model" does not exist and the function fails because the mkdir function doesn't appear to create parent folders. 
Error: 
tensorflow.python.framework.errors_impl.NotFoundError: ../model//modeltemp/
Former-commit-id: e406e75820c4b22beaf617b07f66fe9008cdd8f2 [formerly 39bb28d0c5189bdde6492d22b081014d0d0a5cf9] [formerly 6601008ff2e65f9945d471486efadf73b1aac53a]
Former-commit-id: 579d8dd0f34db508df7b327331b710942ea05cba
Former-commit-id: 2a3041e3d1f8ee5202a37af448d38cb95ee68f1c