Update learning_schedules.py
The following error doesn't occur with the above change in code.

Error: Argument must be a dense tensor: range(0, 3) - got shape [3], but wanted []

The range function on the vairable 'num_boundaries' should be a list! Please merge this request!
Former-commit-id: cb8df57c9c7b22809a45b02175a68ec0a8dfa4f5 [formerly 5fd45d252650037f462b8a72ecb104ad3a890f86] [formerly ef84dca1050762a816984fab7323c5cfea683dde]
Former-commit-id: 3e9d556eed6ff9e581ebd5ef29c787bb47e02ad8
Former-commit-id: bd8e892609ccd1728bc28b66ebd6e0b4b3b3507c