ensure output directory exists
The neural programmer model fails the first time it's run, if the output directory folder does not already exist. In this case "../model" does not exist and the function fails because the mkdir function doesn't appear to create parent folders. 
Error: 
tensorflow.python.framework.errors_impl.NotFoundError: ../model//modeltemp/
Former-commit-id: 19c44a88c0ef488fe0a0dcf93e5de8a3fd07a01a [formerly 1b425b186dc097043d491a2a1c79e1d58919288b] [formerly c8e685b4fabaf0c4a7595f6c429cb44c9e9a2aa6] [formerly 83f1f0b4e0bf1c9ca1e524d8bcc0ed5c51e4f6c2 [formerly 2a3041e3d1f8ee5202a37af448d38cb95ee68f1c] [formerly 579d8dd0f34db508df7b327331b710942ea05cba]] [formerly 215797a9f25cd31bf710eb5365ac8f604df59c1c [formerly e406e75820c4b22beaf617b07f66fe9008cdd8f2 [formerly 39bb28d0c5189bdde6492d22b081014d0d0a5cf9] [formerly 6601008ff2e65f9945d471486efadf73b1aac53a]]]
Former-commit-id: e406e75820c4b22beaf617b07f66fe9008cdd8f2 [formerly 39bb28d0c5189bdde6492d22b081014d0d0a5cf9]
Former-commit-id: 616ef7aaa10fab4120b076751d8d9938a8bfdc4c [formerly be914b43ae94a64836b0cc76cc22b483108c6246] [formerly a3c310493cd6cb3939e7b30522927ab154291129]
Former-commit-id: 5e6607102b8844e38067224365bfb0f1fd9e16d7
Former-commit-id: 587643182efc2385e1473e095239dc9766473a3c