ensure output directory exists
The neural programmer model fails the first time it's run, if the output directory folder does not already exist. In this case "../model" does not exist and the function fails because the mkdir function doesn't appear to create parent folders. 
Error: 
tensorflow.python.framework.errors_impl.NotFoundError: ../model//modeltemp/
Former-commit-id: 6601008ff2e65f9945d471486efadf73b1aac53a
Former-commit-id: 39bb28d0c5189bdde6492d22b081014d0d0a5cf9